// <auto-generated />
namespace Festispec.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update14_38 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update14_38));
        
        string IMigrationMetadata.Id
        {
            get { return "201810291338251_Update-14_38"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
